### ISSUE TITLE
Migrate scenario preparation functionality from `pacta.scenario.preparation/data-raw`

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pacta.scenario.data.preparation#2]
This should be a near refactor, where-in we migrate the data preparation scripts from `pacta.scenario.preparation/data-raw` to exported functions of this package. 

A similar workflow should be added to https://github.com/RMI-PACTA/workflow.scenario.preparation that prepares the scenarios as expected, and saves them in a reasonable location. 

Finally, in https://github.com/RMI-PACTA/workflow.data.preparation/blob/main/run_pacta_data_preparation.R#L103, changes will need to be made to no longer depend on the exported datasets of `pacta.scenario.preparation`. 

After all that is complete, `pacta.scenario.preparation` can be deprecated and archived.

**Comment by jdhoffa** [comment]
FYI. @AlexAxthelm and @cjyetman

**Comment by cjyetman** [comment]
> Finally, in https://github.com/RMI-PACTA/workflow.data.preparation/blob/main/run_pacta_data_preparation.R#L103, changes will need to be made to no longer depend on the exported datasets of `pacta.scenario.preparation`.

Would it instead take in the files created by `[workflow.scenario.preparation](https://github.com/RMI-PACTA/workflow.scenario.preparation)` by specifying an input directory?

**Comment by jdhoffa** [comment]
See here there is a pre-flight path for `Scenarios_AnalysisInput.csv`
I would imagine the safest way would be to just recreate that file in `workflow.scenario.preparation`, and move it from the "pref-flight" to "data inputs" (and delete all of the prep steps in workflow.data.preparation)

**Comment by jdhoffa** [comment]
NIT: My preference would be to actually reformat how `Scenarios_AnalaysisInput.csv` looks to align it with Banks inputs, but I think that would be a next step. "move then improve" and all that

**Comment by jdhoffa** [comment]
Superseded by #12
