### ISSUE TITLE
Decide what to do about semi-internal and manually defined datasets

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pacta.scenario.data.preparation#7]
Currently, in `pacta.scenario.data.preparation` there are several somewhat manually maintained files, that contain "real" data.
These files are used by analysts to define, for example, the technology bridge, or geography bridge files, which may differ per scenario source. 

Currently these are exported by `pacta.scenario.preparation`. 

I am not sure if they should be exported still by `pacta.scenario.data.preparation` or if they should, rather, be required data-file inputs to `workflow.scenario.data.preparation`, found in the `inputs` folder. 

Some examples of these files:
https://github.com/RMI-PACTA/pacta.scenario.preparation/blob/main/data-raw/scenario_source_pacta_geography_bridge.R
https://github.com/RMI-PACTA/pacta.scenario.preparation/blob/main/data-raw/technology_bridge.csvhttps://github.com/RMI-PACTA/pacta.scenario.preparation/blob/main/data-raw/scenario_regions.csv

cc: @cjyetman @AlexAxthelm thoughts?

AB#9892

**Comment by AlexAxthelm** [comment]
I suggest taking the same path we did for `workflow.factset`, and externalizing the data (`data-raw` and `data` directories are removed), and making them necessary inputs.

**Comment by jdhoffa** [comment]
Thanks, I tend to agree!

**Comment by cjyetman** [comment]
specific geography and technology bridges for each scenario source are now maintained here
https://github.com/RMI-PACTA/pacta.scenario.data.preparation/tree/main/data-raw

"methodologically", I think it makes sense to maintain those bridges here in this pkg/repo, where all other "decisions" about the raw data are made.

can this be considered closed then?

**Comment by jdhoffa** [comment]
Happy to!
